### ISSUE TITLE
Check-in page welcome page (For weeks when check-in period is not open)

### ISSUE THREAD

**Issue by sanuann** [greenstreetsinitiative/checkin2015#2]

**Comment by sanuann** [comment]
In the 2nd paragraph after the date, change from:
“And, if your company is participating in the Corporate Challenge, your monthly Walk/Ride Day check-ins from April through October will count towards your company's standings.” 
to 
“And, if your company is participating in the [Corporate Challenge](http://gogreenstreets.org/2016-walkride-day-corporate-challenge), your monthly Walk/Ride Day check-ins from April through October will count towards your company's standings.”

**Comment by ghost** [comment]
This has been completed.
