### ISSUE TITLE
Remove use of Mandrill for the Retail app

### ISSUE THREAD

**Issue by thecristen** [greenstreetsinitiative/checkin2015#21]
Right now it's used to send email notifications to Green Streets when new Retail Partner form is filled. We can do this with Python...

**Comment by thecristen** [comment]
Testing out some changes I'm making to this... @jkatzchristy did `info@greenstreets.org` get an email a few minutes ago for a new retail partner I made? :)

**Comment by thecristen** [comment]
Adding this note -

Mandrill still is needed to play the part of the email server - see relevant settings https://github.com/greenstreetsinitiative/checkin2015/blob/master/checkin2015/settings.py#L182
How to replace this? We'll have to look into other email servers. Does Google Apps provide anything? Something else?

**Comment by stephoj** [comment]
Can we use elastic email? Janie has an account under her email and typical password. Mandrill is due to stop sending emails 4/27.

**Comment by thecristen** [comment]
@stephoj @jkatzchristy apparently I don't remember the password. Could one of you log in and tell me the API Key? Feel free to email it to me. The site says:

>  you can find your API Key from the Account Profile tab on your dashboard

**Comment by jkatzchristy** [comment]
gst****s

Warmly,
Janie

_Janie Katz-Christy, Director_
_Green Streets Initiative http://gogreenstreets.org/_
_617-299-1872 o_
_617-645-9678 c_
_[image: gogreenstreets.org] http://gogreenstreets.org/_
_Happy Walk/Ride Day Week! *_Check in
http://checkinapp-greenstreets.rhcloud.com/checkin/ *_your plans now for
this Friday's Walk/Ride Day._
_Friend us on Facebook
https://www.facebook.com/pages/The-Green-Streets-Initiative/67566090954,
follow us on Twitter http://twitter.com/walkridedays and Instagram
https://instagram.com/gogreenstreets/._

**Comment by thecristen** [comment]
Great, I think this will work out well! Will implement this later today.
