### ISSUE TITLE
VERY HIGH PRIORITY Make sub-teams field dynamic

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#23]
Sub-teams field currently shows up always, and shows ALL sub-teams. 

PRIORITY #!: Sub-teams field should ONLY show IF employer selected HAS sub-teams. Show only the sub-teams related to specific selected employer.

(Participants have no way to know if their company had subteams or not, nor which sub-teams on this very long list relate to their workplace!)

PRIORITY #2: Leaderboard needs to show ALL employers with sub-teams.

**Comment by jkatzchristy** [comment]
**\* 2015 and 2014 Check-ins and Leaderboards showed worked in the correct way re sub-teams, I believe ***

**Comment by thecristen** [comment]
I just pushed a fix for the first item! Now the subteam menu only shows if you picked an employer that has subteams. Additional, the resulting list of subteams is filtered by subteams that are in the selected team!

![subteamselect](https://cloud.githubusercontent.com/assets/2136286/14775824/d6db6502-0a8f-11e6-8d2f-397d9f4a9677.gif)

 Checking the entities listed in http://checkinapp-greenstreets.rhcloud.com/companies/2016/ against the employers listed in the "Looking for a Sub-Team?" menu on the LB confirms that they're all in there.
