### ISSUE TITLE
Investigate keeping records of what emails sent by app

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#24]
Per Troy's request.

**Comment by pwnage101** [comment]
We at least want a record of what emails are sent, and if they are accepted by the mail server.  Apparently we get that for free with Mandrill.

The task here is to confirm that we have that now with whatever sends mail, or to figure out a way to collect that information.  Even just a script to parse the django logs would be better than nothing.

**Comment by thecristen** [comment]
Now we're using Elastic Email for send emails! And we can now see the emails being sent simply by logging in https://elasticemail.com/account#eactivitylogbox. So this is probably complete. :)
