### ISSUE TITLE
(HIGHEST PRIORITY: STEP 1) Add "question of the month" near end of check-in

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#28]
Step 1: Change text in comment text box FROM "On a rainy spring day, what's your favorite mode of commuting?" TO 
"April's question-of-the-month: If you could designate a road in the Greater Boston Area (or in your area if you are elsewhere) to have a safe-for-biking lane, which road or stretch of road would you pick?"

Step 2: If it's possible, add new question before "Add a Comment" to be changed each month:

"April's question-of-the-month: If you could designate a road in the Greater Boston Area (or in your area if you are elsewhere) to have a safe-for-biking lane, which road or stretch of road would you pick?" +[text box]

**Comment by jkatzchristy** [comment]
@pwnage101 Can you work on this?!

**Comment by pwnage101** [comment]
technical consideration: if we add the text box and change the model, how does this affect old rows?  Do all the existing database rows need to be modified?  What part of this problem does Django tooling help with.

**Comment by jkatzchristy** [comment]
Step 1: Change text in comment text box FROM "On a rainy spring day, what's your favorite mode of commuting?" TO 
"April's question-of-the-month: If you could designate a road in the Greater Boston Area to have a safe-for-biking lane, which road or stretch of road would you pick?"

Step 2: Add new question before "Add a Comment" to be changed each month: 

"April's question-of-the-month: If you could designate a road in the Greater Boston Area to have a safe-for-biking lane, which road or stretch of road would you pick? ______________________"

**Comment by jkatzchristy** [comment]
@thecristen Troy just told me he's going to be out for 3 hours... we've been waiting to welcome coordinators to the new check-in until Step 1 change is made. Can you do it now, by any chance? Or is it something Dustin can do?

Thanks!!

**Comment by thecristen** [comment]
Wow, that changed from Lower Priority real quick. Not great.
I can address it now, by doing what you outlined in Step 1. Adding an entirely new question is a more substantial change which we could consider next month.

**Comment by jkatzchristy** [comment]
Yes, sorry for changing the priorities on you. It had been lower priority than getting people to the check-in and getting the links made to leaderboard... Thank you for doing it!!!

And can you add "(or in your area if you are elsewhere)"? It turns out that we ARE getting check-ins from all over the world! @thecristen

**Comment by thecristen** [comment]
I'm out right now but can change it in about an hour

**Comment by jkatzchristy** [comment]
THANK YOU!
