### ISSUE TITLE
Change text in comment box

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#29]
Current grey text in "Add a comment" box that says "Employers may now register..." is out of date.
Replace with either "We welcome your feedback here!", whatever we had there in 2015, or text from Issue #28.

**Comment by thecristen** [comment]
The new site has it - http://checkinapp-greenstreets.rhcloud.com/checkin/
It has Stephanie's suggestion - "On a rainy spring day, what is your favorite mode of commuting?"
