### ISSUE TITLE
Phone number in thank you email has extra space

### ISSUE THREAD

**Issue by thecristen** [greenstreetsinitiative/checkin2015#30]
Seen in my Gmail inbox.

The [relevant bit of code](https://github.com/greenstreetsinitiative/checkin2015/blob/master/survey/views.py#L184) has no space, so I'm quite perplexed by this one.

**Comment by pwnage101** [comment]
At a glance, it looks like there's no closing span tag.  HTML engines in web browsers might be able to handle those special cases with an appropriate doctype, but I assume email clients are hit-or-miss.
