### ISSUE TITLE
IMPORTANT FOR MONDAY: Confirm that correct subteams are being used

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#32]
The employers and subteams that are correct for 2016 were entered here: http://checkinapp-greenstreets.rhcloud.com/admin/survey/team/. 

They do not seem to be the same ones that are on the current live check-in.

**Comment by thecristen** [comment]
Checking on this. Are there any specific subteams that are missing or that are there and shouldn't be?

**Comment by thecristen** [comment]
The checkin shows all Teams whose associated Employer is checked as participating is the 2016 challenge. I updated **BU** and **NMR group** - The 2015-participant was still marked as 2016 even though there are separate 2016-participant entries for them. 

By the way the entities listed at http://checkinapp-greenstreets.rhcloud.com/companies/2016/ are what's feeding the LB and checkin :)

**Comment by jkatzchristy** [comment]
I think this is all clarified/resolved.
