### ISSUE TITLE
Redirect all other check-in urls to our current one

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#33]
Currently, our historical check-in url, checkin.gogreenstreets.org, REDIRECTS TO THE WRONG check-in URL: checkin2015-greenstreets.rhcloud.com. 
1. Redirect checkin2015-greenstreets.rhcloud.com to http://checkinapp-greenstreets.rhcloud.com/checkin/.
2. Redirect checkin.gogreenstreets.org to http://checkinapp-greenstreets.rhcloud.com/checkin/ - if you have access to that.

**Comment by pwnage101** [comment]
checkin.gogreenstreets.org resolves to 184.168.221.6 which just responds with a 301 redirect. 184.168.221.6 is not openshift (since it's not AWS).  What is this server?  Who has access?

**Comment by pwnage101** [comment]
Another solution would be to implement the following CNAME record at the DNS server

`checkin.gogreenstreets.org CNAME checkinapp-greenstreets.rhcloud.com.`

GoDaddy is the DNS provider.  How does this solution sound instead?

**Comment by jkatzchristy** [comment]
I will ask our GoDaddy owner, the first person who reserved our url, to redirect. In the meantime, and as well, can you do item 1?

**Comment by pwnage101** [comment]
Yes, I'll create a separate "redirect_to_checkinapp" branch to redirect the 2015 app.  I will not merge this into master since this will only be for use with the 2015 app.

**Comment by jkatzchristy** [comment]
Great! Is it close to happening?

**Comment by jkatzchristy** [comment]
ONE MORE NOTE!: The check-in button on our website now goes straight to page 2 of our check-in (http://checkinapp-greenstreets.rhcloud.com/checkin/), so people have one less click to make! 

We will still probably want to integrate some of the text and graphics from page 1 (http://checkinapp-greenstreets.rhcloud.com/), but that's not our highest priority. Though @pwnage101  is working on this, I wanted to make sure that @thecristen is aware of this.

**Comment by pwnage101** [comment]
created commit acda8b251711d6ee3e0c62f475e8daf6f7d0e44c in branch redirect_to_checkinapp.  I will be deploying this to checkin2015-greenstreets.rhcloud.com as soon as i fix my clogged toilet....

**Comment by jkatzchristy** [comment]
:) Great! Good luck on both.

**Comment by pwnage101** [comment]
deployment to checkin2015-greenstreets in progress.

**Comment by pwnage101** [comment]
Redirection via Django appears to be successful!  As it stands:

checkin.gogreenstreets.org points to mystery server 184.168.221.6 which returns a 301 redirect to checkin2015-greenstreets.rhcloud.org which returns a 301 redirect to checkinapp-greenstreets.rhcloud.org.

**Comment by jkatzchristy** [comment]
Can you change the destination page to  http://checkinapp-greenstreets.rhcloud.com/checkin/ (page 2 of checkin?) @pwnage101

**Comment by pwnage101** [comment]
Just to be clear, I actually deployed the commit df49960e17b0b70a1a19532165b856d403f603cf in branch redirect_to_checkinapp_2.  This is different in the sense that the parent of HEAD is what used to be deployed to checkin2015-greenstreets.rhcloud.com.  I've done this in an attempt to minimize any harmful changes.

**Comment by pwnage101** [comment]
Spoke with janie over the phone, re her request to update the destination page to /checkin/.  This might have an undesirable effect, and it needs to be specced out more.

Keep this issue open until we make the DNS change and verify that it is successful and doesn't break anything.

**Comment by pwnage101** [comment]
still waiting on that DNS propagation.  Meanwhile, I ran this just for fun:

```
sankeytm@node2:~$ wget -O /dev/null checkin.gogreenstreets.org
--2016-04-25 15:18:46--  http://checkin.gogreenstreets.org/
Resolving checkin.gogreenstreets.org (checkin.gogreenstreets.org)... 184.168.221.6
Connecting to checkin.gogreenstreets.org (checkin.gogreenstreets.org)|184.168.221.6|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://checkin-greenstreets.rhcloud.com [following]
--2016-04-25 15:18:46--  http://checkin-greenstreets.rhcloud.com/
Resolving checkin-greenstreets.rhcloud.com (checkin-greenstreets.rhcloud.com)... 54.173.203.216
Connecting to checkin-greenstreets.rhcloud.com (checkin-greenstreets.rhcloud.com)|54.173.203.216|:80... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: http://checkin2015-greenstreets.rhcloud.com/ [following]
--2016-04-25 15:18:47--  http://checkin2015-greenstreets.rhcloud.com/
Resolving checkin2015-greenstreets.rhcloud.com (checkin2015-greenstreets.rhcloud.com)... 54.173.243.29
Connecting to checkin2015-greenstreets.rhcloud.com (checkin2015-greenstreets.rhcloud.com)|54.173.243.29|:80... connected.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: http://checkinapp-greenstreets.rhcloud.com/ [following]
--2016-04-25 15:18:47--  http://checkinapp-greenstreets.rhcloud.com/
Resolving checkinapp-greenstreets.rhcloud.com (checkinapp-greenstreets.rhcloud.com)... 52.91.162.240
Connecting to checkinapp-greenstreets.rhcloud.com (checkinapp-greenstreets.rhcloud.com)|52.91.162.240|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `/dev/null'

    [ <=>                                                                                                    ] 8,915       --.-K/s   in 0s

2016-04-25 15:18:47 (248 MB/s) - `/dev/null' saved [8915]

sankeytm@node2:~$
```

Basically:
1. `checkin.gogreenstreets.org` resolves to `184.168.221.6`
2. `184.168.221.6` redirects to `checkin-greenstreets.rhcloud.com`
3. `checkin-greenstreets.rhcloud.com` resolves to an IP address which 301 redirects to `checkin2015-greenstreets.rhcloud.com`
4. `checkin2015-greenstreets.rhcloud.com` resolves to an IP address which 301 redirects to `checkinapp-greenstreets.rhcloud.com`
5. `checkinapp-greenstreets.rhcloud.com` resolves to an IP address which returns the site.

It's an interesting song and dance.  Oh well, it works for now.

After the CNAME record gets propagated, `checkin.gogreenstreets.org` will be an alias for `checkinapp-greenstreets.rhcloud.com`, so `checkin.gogreenstreets.org` should immediately resolve to whatever `checkinapp-greenstreets.rhcloud.com` resolves to. My assertion is that you will see the following in the browser: `http://checkin.gogreenstreets.org/`

**Comment by pwnage101** [comment]
won't have time to work on anything until later this evening

**Comment by jkatzchristy** [comment]
I closed the old check-in, thanks to Cristen's suggestion, something I should have thought of doing much earlier!

**Comment by stephoj** [comment]
@jkatzchristy and I will ensure all links are correct from the website and ensure that we send the correct links in communications.
