### ISSUE TITLE
TUESDAY, HIGHEST PRIORITY: Integrate checkins from obsolete form into current LB

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#38]
For whatever reason, ACIS staff are still checking in on http://checkin2015-greenstreets.rhcloud.com/ this morning. Therefore, their check-ins are not being sent to our current leaderboard, nor are they seeing the Question of the Month. Those check-ins need to be integrated into http://checkinapp-greenstreets.rhcloud.com/leaderboard/2016/ ASAP. @thecristen @pwnage101 Can you make this happen?!

**Comment by thecristen** [comment]
@jkatzchristy Why didn't you close http://checkin2015-greenstreets.rhcloud.com/ to new checkins?!?! Just set the close date!

**Comment by jkatzchristy** [comment]
Smart! And really dumb of me. I somehow thought that the dates on the home
page would be confusing. Anyhow, done now.

Warmly,
Janie

_Janie Katz-Christy, Director_
_Green Streets Initiative http://gogreenstreets.org/_
_617-299-1872 o_
_617-645-9678 c_
_[image: gogreenstreets.org] http://gogreenstreets.org/_
_Happy Walk/Ride Day Week! *_Check in
http://checkinapp-greenstreets.rhcloud.com/checkin/ *_your plans now for
this Friday's Walk/Ride Day._
_Friend us on Facebook
https://www.facebook.com/pages/The-Green-Streets-Initiative/67566090954,
follow us on Twitter http://twitter.com/walkridedays and Instagram
https://instagram.com/gogreenstreets/._

**Comment by thecristen** [comment]
phew... it was even harder than I thought, but I DID IT. I took all checkins from the old site made 4/22 or later (everything before was already in), and entered them into the new site. Marking this complete
