### ISSUE TITLE
Check-in page (http://checkin2015-greenstreets.rhcloud.com/checkin/)

### ISSUE THREAD

**Issue by sanuann** [greenstreetsinitiative/checkin2015#4]
- ADD SEPARATE NUMBER/ STREET/ ZIP CODE FIELDS FOR BOTH HOME AND WORK ADDRESS: We could not analyze for location b/c there were too many home and work address typos.
- TEXT MODIFICATIONS: 
  - Substitute with/revert to "Employer" for "Occupation" 
  - Modify wording to:"Use 'Not employed', 'Self', 'Student' or 'Other employer' as appropriate" (before April) and 
  - "Use 'Not employed', 'Self', 'Student' or 'Other employer not involved in the Corporate Challenge' as appropriate" (after April)
  - Remove "or team" from: "Green Streets Initiative will not shnot are identifying information with any organization, other than your employer [or team] if participating in the Corporate Challenge (from April through October). You may opt out of sharing your information with your employer below. 
  - Add an \* to "YOUR WALK/RIDE DAY\* COMMUTE"
  - Add note below "YOUR WALK/RIDE DAY\* COMMUTE":
  
  "Please enter all segments (legs) of your commute and the approximate duration of each segment. Include walking as an additional segment (e.g. walking from the bus stop to a connecting train). Feel free to check in early, before your actual commute. You can go back and make changes; the system will record only your most recent submission. 
  
  *If you don't work on Fridays or for another reason, you may substitute another day to detail as your "Walk/Ride Day" commute.”
  - Add note below "YOUR "NORMAL DAY COMMUTE":"Please enter all segments (legs) of your commute and also include time spent walking as an additional segment (e.g. walking from the bus stop to a connecting train). If you commute in a variety of ways, depending on the day, just pick one that you think is your most typical."
  - Add note after "Comments" (TEMPORARY UNTIL 4/15/2016): "Employers may now register for the ​2016 Walk/Ride Day Corporate Challenge. ​Registration deadline is April 14(discounts for early registration). If you would like us to invite your employer​:  **_[Name of employer]           Would you like us to mention you? _yes/no_**_."
  - Resurrect wording from COMMENTS from 2014 Check-in. It/they elicited much more thoughtful responses. 
- SIMPLIFY CHECK-IN: Add check-box that says: "Same" to last 3 commute choices, automatically fill fields from home to work/ from work to home.
- UPDATE: Ensure employer list is complete with 2016 competitors complete before April 22nd.
- ICONS Use social media icons from website.

**Comment by ghost** [comment]
Text modifications have been completed.  All set on social media icons.  Employer list will be updated by Janie/Stephanie through the site's admin console.  Highest priority task remaining is to simplify the checkin, based on how it was set up in the sample checkin site.

**Comment by jkatzchristy** [comment]
Created #22.

**Comment by thecristen** [comment]
Created #31. Everything else seems to be done, so closing this.
