### ISSUE TITLE
Remove cookies from comment section

### ISSUE THREAD

**Issue by stephoj** [greenstreetsinitiative/checkin2015#41]
Confirm cookies work for entire check-in form, except for 'Add a comment' area. At the moment, it looks like the top half has cookies, the legs (time/mode) don't have cookies (#42) and the comment box does have cookies. Please remove cookies from comment section.

**Comment by jkatzchristy** [comment]
@thecristen @pwnage101 Have cookies been removed from Comments section, ie. can this issue be closed? Also, can all the issues that have been done be closed? Stephanie and I are trying to understand what has been done already, and what still needs to be done. Thanks!
