### ISSUE TITLE
Have cookies remember past transportation (mode+time)

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#42]
Currently, modes and time seem to need to be re-selected each time one check's in. It would be much easier if they could be remembered, so people would not have to enter their commutes each time. Some people have complicated multi-leg commutes.

Comment from a participant's check-in yesterday:
"I wish this page would save my check-in information rather than requiring me to post it all each time."

**Comment by jkatzchristy** [comment]
@thecristen @pwnage101:  typical reaction people have is voiced again, here:
13097 Boston University (Staff) - BU MED    "Why do I have to do this manually every month, when it is always the same?  Can you not save the route, so I can check in faster. It takes too much time, and I will probably stop doing it for that reason." 
I appreciate his sharing what I know many people feel.

**Comment by thecristen** [comment]
Status update: I've made some changes so that all the legs will now be **saved** in cookies. I've not yet made the complementary change of showing the saved cookie legs on the form. So you won't see this on the page yet, but this is good progress towards being able to display people's chosen legs the next month!

**Comment by stephoj** [comment]
Update?

**Comment by pwnage101** [comment]
@jkatzchristy what's the status on this?

**Comment by jkatzchristy** [comment]
Done. Here's the test version:
http://checkintest-greenstreets.rhcloud.com/checkin/

*Janie Katz-Christy, Director*
*Green Streets Initiative <http://gogreenstreets.org/>*
*617-299-1872 o*
[image: gogreenstreets.org]
*Sign up <http://checkin.gogreenstreets.org/> to be reminded about upcoming
Walk/Ride Days.*
*Make sure *your employer is registered for the 2017 Challenge
<http://tracking.gogreenstreets.org/tracking/click?msgid=_ezeu2IAKKpNWtd2dnxdsA2&target=http%3a%2f%2fwww.gogreenstreets.org%2fsites%2fall%2fmodules%2fcivicrm%2fextern%2furl.php%3fu%3d4979%26qid%3d844294&v=6svswCy11OwKE-Bv_z8O0A2>
!
*Friend us on Facebook
<https://www.facebook.com/pages/The-Green-Streets-Initiative/67566090954>,
follow us on Twitter <http://twitter.com/walkridedays> and Instagram
<https://instagram.com/gogreenstreets/>.*
