### ISSUE TITLE
IMMEDIATE: Confirm that server will not crash

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#43]
When I try to see April 2016 check-ins (" commuter surveys") to download them, I get this error message: 
"504 Gateway Time-out
The server didn't respond in time."
@thecristen @pwnage101 do you know why or how to correct? I don't want the server to have problems when more people are checking in tomorrow.

**Comment by thecristen** [comment]
To avoid this problem in the mean time, don't download more than a few checkins at a time while the checkin is open.  Don't do it!

**Comment by jkatzchristy** [comment]
OK, I won't download much. Did you check to make sure that all commutes are being captured?

**Comment by thecristen** [comment]
Looking in the admin at the Legs table, it looks like all commutes are being captured perfectly! :)

(The table shows all legs, and you can tell which ones are part of one person's commuter because they have the same identifier number for "checkin")
