### ISSUE TITLE
HIGHEST PRIORITY MONDAY: Fix LB percentages 

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#44]
Currently, companies that have 100% of staff checked in show up as 25%  @thecristen is that bc.
 the LB is calculating for all 4 months of 2016 so far? It's important to correct asap or ar.least confirm so we can tell coordinators of those workplaces that are at or.near 100% so they are.not.unnecessarily harassing staff to check in. Please confirm, if not correct asap. THANKS!

**Comment by thecristen** [comment]
Please name a company so I can check.

**Comment by thecristen** [comment]
@jkatzchristy I think your intuition was right that it was including too many months. I've adjusted the relevant code... should I push it online now or wait until later in the day? It'll take down the site for a minute or two.

**Comment by jkatzchristy** [comment]
THANK YOU SO MUCH!!

Warmly,
Janie

_Janie Katz-Christy, Director_
_Green Streets Initiative http://gogreenstreets.org/_
_617-299-1872 o_
_617-645-9678 c_
_[image: gogreenstreets.org] http://gogreenstreets.org/_
_Happy Walk/Ride Day! *_Check in
http://checkinapp-greenstreets.rhcloud.com/checkin/ *_your commute, any
commute, now!_
_Friend us on Facebook
https://www.facebook.com/pages/The-Green-Streets-Initiative/67566090954,
follow us on Twitter http://twitter.com/walkridedays and Instagram
https://instagram.com/gogreenstreets/._
