### ISSUE TITLE
Clear cookies when checking in another person

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#46]
At the end of the check-in, it says "Thank you... Check in another participant or go to the Leaderboard". But if you click on "Check in another participant", all the first participant's info is retained. We had some coordinators trying to check people in outside or in the lobby, and this was very inconvenient for them.

**Comment by thecristen** [comment]
Can we tell people hosting checkin stations in public stations to _use the private mode on their browser_? I think most browsers have this option nowadays. then it won't store people's info

**Comment by jkatzchristy** [comment]
Brilliant! Then it should have a note to that effect near where it says "Check
in another person"? Eg. like:
"_Check in another person_ (use "incognito window" or "private mode" in
browser)"

**Comment by stephoj** [comment]
We will advise coordinators to use incognito or private browsers when mass staff are checking in on the one computer.

**Comment by stephoj** [comment]
When person clicks "check-in another person" that person needs to be directed to an incognito or private browser to complete their check-in

**Comment by pwnage101** [comment]
The code in PR #51 currently deletes the session cookie when the "Check in another participant"  is pressed, but do we want to actually delete the session cookie?  Is there no use case for remembering original form values after submitting a referral checkin?

**Comment by thecristen** [comment]
Good question @pwnage101!! It inspired to me to reflect a whole lot on my approach. Then I remembered we'd agreed to just make people use Incognito Mode instead, and that I was going to put a notice about that on the site. I'll revert the previous change I'd made.

BTW @stephoj, it is not possible to redirect someone to an incognito window. This looks like it will just be something we have to depend on the user to handle properly themselves.

**Comment by stephoj** [comment]
We have communicated to coordinators to check-in mass groups of people in incognito browsers.
