### ISSUE TITLE
Update Sample Check-in

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#47]
The current Sample Check-in shows the 2015 check-in, and needs to be changed to show the 2016 Check-in. (The Sample Check-in enables us to see and to show others what the check-in looks like, even  allows Currently, when the Check-in is closed.) Determine process to keep it always updated.

**Comment by stephoj** [comment]
Take screenshots of sample check-in and delete sample check-in.

**Comment by stephoj** [comment]
@jkatzchristy or @thecristen will take screen shots of the check-in.
