### ISSUE TITLE
dead link to retail page on gogreenstreets home page

### ISSUE THREAD

**Issue by pwnage101** [greenstreetsinitiative/checkin2015#59]
See link to retail page on http://gogreenstreets.org/

It should point to:

http://checkin.gogreenstreets.org/retail/

...but instead it points to a non-existent app:

http://checkin-greenstreets.rhcloud.com/retail/

**Comment by thecristen** [comment]
Why not point to http://**checkinapp**-greenstreets.rhcloud.com/retail/ ?

Also, not sure this issue belongs here, as http://gogreenstreets.org/ is a completely different site than this django app.

**Comment by jkatzchristy** [comment]
Oooh, thanks!!! We missed that. Fixed now.
