### ISSUE TITLE
Update Thank You letter

### ISSUE THREAD

**Issue by sanuann** [greenstreetsinitiative/checkin2015#6]
- Changes can be found [here](https://docs.google.com/document/d/1wti4SOhVIruEekD1QhA-nj8ifa1WsDI-BtQ7HN8bWL8/edit)
- Once leaderboard is live April- October be sure to send out thank you email with ‘To see how your company is ranked in the 2016 Walk/Ride Day CORPORATE CHALLENGE, click here (hyperlink)’ instead of, ‘If you haven't already, CLICK HERE to see how your company did in the 2015 Corporate Challenge, which ended with the October Walk/Ride Day.’ Ensure change of thank you letter occurs before March 29th

**Comment by jkatzchristy** [comment]
Replaced by #28
