### ISSUE TITLE
Text changes to checkin and checkintest

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#63]
In both checkin and checkintest, make the following text changes under "Your Normal Day Commute" 

1.  In both "TO WORK" and "FROM WORK", in  "MY NORMAL COMMUTE IS EXACTLY LIKE MY WALK RIDE DAY COMMUTE.", change "WALK RIDE DAY" to "WALK/RIDE DAY", ie add "/".
2.  If one answers "No", 

- change text In "TO Work FROM Home" from "How you did, or will, travel:" to "How you typically travel on Fridays (or on another day you choose to compare with your Walk/Ride Day):"

- In "FROM Work TO Home", change "I did, or will, travel the same way as I did, or will travel TO work, but in reverse:" to "I usually travel the same way as I typically travel TO work, but in reverse."

- If respondent answers "No" to the above item, change "How you did, or will, travel:" to ""How you typically travel:"

**Comment by pwnage101** [comment]
is checkintest a staging environment that we can use to test changes?

**Comment by jkatzchristy** [comment]
Yes. (and is here: http://checkintest-greenstreets.rhcloud.com/checkin/).

Also, because the actual check-in is only open during the actual Walk/Ride
Day check-in period, we use the checkintest during the rest of the month to
show others how the check-in process takes place.

*Janie Katz-Christy, Director*
*Green Streets Initiative <http://gogreenstreets.org/>*
*617-299-1872 o*
[image: gogreenstreets.org]
*Sign up <http://checkin.gogreenstreets.org/> to be reminded about upcoming
Walk/Ride Days.*
*Make sure *your employer is registered for the 2017 Challenge
<http://tracking.gogreenstreets.org/tracking/click?msgid=_ezeu2IAKKpNWtd2dnxdsA2&target=http%3a%2f%2fwww.gogreenstreets.org%2fsites%2fall%2fmodules%2fcivicrm%2fextern%2furl.php%3fu%3d4979%26qid%3d844294&v=6svswCy11OwKE-Bv_z8O0A2>
!
*Friend us on Facebook
<https://www.facebook.com/pages/The-Green-Streets-Initiative/67566090954>,
follow us on Twitter <http://twitter.com/walkridedays> and Instagram
<https://instagram.com/gogreenstreets/>.*
