### ISSUE TITLE
Add new QOM format to check-in

### ISSUE THREAD

**Issue by jkatzchristy** [greenstreetsinitiative/checkin2015#75]
http://checkinapp-greenstreets.rhcloud.com/admin/survey/questionofthemonth/add/
Enable new QOM format for new questions.
(Note: I could not add ANY new check-in months to the dev or test checkin sites, for some reason. Was trying to add one for March and test out the new QOM format options.

**Comment by rrballenger17** [comment]
Regarding "(Note: I could not add ANY new check-in months...", there was an issue with the database but it's resolved.
