### ISSUE TITLE
Checkins can be submitted without commute information

### ISSUE THREAD

**Issue by ghost** [greenstreetsinitiative/checkin2015#9]
On the main checkin page, required fields are working for things like email address and employer, but are not working for fields in the From and To on WR Day and Normal day.  So, bad data (incomplete) can be introduced into our checkin database.  We need to change this so users are forced to fill out all key fields before they can successfully submit a checkin.  As far as we can tell, this issue is not a new one and has been around since last year.

**Comment by thecristen** [comment]
Fixed in ec19e43
